version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./prisma:/app/prisma
      - sqlite-data:/app/data
    restart: unless-stopped

volumes:
  sqlite-data:
